-   id: gt-commit-msg
    name: gt-commit-msg
    entry: jolly_github_toolbelt/hooks/commit-msg
    language: script
    require_serial: true
    description: 'gt-commit-message: Build good commit messages'
    minimum_pre_commit_version: 0.15.4
    stages: [commit-msg]
-   id: gt-self-check
    name: gt-self-check
    entry: jolly_github_toolbelt/hooks/pre-commit
    language: script
    require_serial: true
    description: 'gt-self-check: Run self-check (if present)'
-   id: gt-prepare-commit-msg
    name: gt-prepare-commit-msg
    entry: jolly_github_toolbelt/hooks/prepare-commit-msg
    language: script
    require_serial: true
    description: 'gt-prepare-commit-msg: Build commit messages based on the branch name'
    minimum_pre_commit_version: 1.16.0
    stages: [prepare-commit-msg]
